import styles from '../styles/Home.module.scss'

import type { NextPage } from 'next'
import Head from 'next/head'
import TokensListComponent from '../components/TokensListComponent'
import OdcLogo from '../assets/images/odc-logo.png';
import { useState } from 'react';
import { useDebounce } from 'use-debounce';
import Favicon from '../assets/images/icon.png';

const Home: NextPage = () => {
  const [ collectionQuery, setCollectionQuery ] = useState("");
  const [ debouncedCollectionQuery ] = useDebounce(collectionQuery, 200);

  return (
    <>
      <Head>
        <title>Open Devs Crew Gallery</title>
        <meta name="description" content="Generated by create next app" />

        <meta property="og:title" content="Next Website"></meta>
        <meta property="og:type" content="website"></meta>
        <meta property="og:image" content="#"></meta>
        <meta property="og:url" content={`${process.env.NEXT_PUBLIC_BASE_URL}/`}></meta> 

        <link rel="icon" href={Favicon.src} />
      </Head>

      <main className={styles.main}>

        <div className={styles.titleBar}>
          <div>
            <img src={OdcLogo.src} alt="Open Devs Crew logo" />
            <h1>Token Gallery</h1>
          </div>
          <input
            placeholder='Search Token ID'
            type={'number'}
            value={collectionQuery}
            onChange={(e) => setCollectionQuery(e.target.value)}
          />
        </div>

        <TokensListComponent queryParam={debouncedCollectionQuery} />
      </main>
    </>
  )
}

export default Home
